### ISSUE TITLE
运行速度比flatpak快多了，不知道啥时候会有录音的功能

### ISSUE THREAD

**Issue by haol666** [liudonghua123/scratch-app#1]
需要录音功能。

**Comment by liudonghua123** [comment]
这个项目仅仅是对 [scratch-gui](https://github.com/scratchfoundation/scratch-gui) 的简单封装，不添加额外的功能、特性，可以在 [scratch-gui](https://github.com/scratchfoundation/scratch-gui) 项目中提交相关功能
